### ISSUE TITLE
google_compute_node_group is missing from the supported list of resources

### ISSUE THREAD

**Issue by sjourdan** [snyk/driftctl-docs#205]
Since 0.18 and https://github.com/snyk/driftctl/pull/1250 driftctl supports `google_compute_node_group`

**Comment by wbeuil** [comment]
I added the resource in the latest PR for v0.18.0 https://github.com/snyk/driftctl-docs/pull/204

**Comment by wbeuil** [comment]
you can view the missing resource in the latest documentation https://docs.driftctl.com/0.18.0/providers/google/resources
